version: '3.8'

services:
  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: goapp
      MYSQL_USER: go
      MYSQL_PASSWORD: go
    ports:
      - "3307:3306"
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
    environment:
      PORT: 8080
      DB_USER: go
      DB_PASSWORD: go
      DB_NAME: goapp
      DB_HOST: db
      DB_PORT: 3306

volumes:
  dbdata:
